(function () {
  'use strict';
  const $ = id => document.getElementById(id); if (!$('imSet')) return;
  const BR = CV.BR, D = CVData.D, esc = CVDialog.esc, TODAY = CVData.TODAY;
  const E = { reg: ['Registered', 'Unregistered'], sp: ['Dog', 'Cat'], sx: ['Male', 'Female'], st: ['Yes', 'No', 'Scheduled'], ar: ['Up to date', 'Due soon', 'Not vaccinated'], pt: ['Barangay Paravet', 'Mobile Paravet'], cs: ['Submitted', 'Pending'], cd: ['Vaccinated', 'Caged', 'Tied', 'Free', 'Stray'], pi: ['Willing', 'Undecided', 'Not interested'] };
  // col: [header, field, type, hint, optional]
  const S = {
    owners: { label: 'Owners', cols: [['owner_name', 'name', 't', 'Text, e.g. Reyes, Alex'], ['mobile', 'mobile', 'm', '09XX-XXX-XXXX (may be blank)', 1], ['barangay', 'barangay', 'b', 'Official barangay name (62)'], ['source', 'source', CV.SRC], ['registration_status', 'status', E.reg], ['date_registered', 'date', 'd', 'YYYY-MM-DD']], key: r => [r.name, r.barangay], extra: { pets: 0 } },
    pets: { label: 'Pets', cols: [['pet_name', 'name', 't', 'Text'], ['species', 'species', E.sp], ['sex', 'sex', E.sx], ['age_years', 'age', 'a', 'Number 0–30 (may be blank)', 1], ['owner_name', 'owner', 't', 'Text'], ['barangay', 'barangay', 'b', 'Official barangay name (62)'], ['registration_status', 'status', E.reg], ['sterilized', 'sterilized', E.st], ['anti_rabies', 'rabies', E.ar], ['source', 'source', CV.SRC], ['date_registered', 'date', 'd', 'YYYY-MM-DD']], key: r => [r.name, r.owner, r.barangay], extra: {} },
    paravets: { label: 'Paravets', cols: [['paravet_name', 'name', 't', 'Text'], ['type', 'type', E.pt], ['barangay', 'barangay', 'p', 'Official barangay, or All (rotating) for Mobile'], ['mobile', 'mobile', 'm', '09XX-XXX-XXXX (may be blank)', 1], ['census_summary', 'census', E.cs], ['animals_recorded', 'animals', 'n', 'Whole number'], ['date_submitted', 'date', 'd', 'YYYY-MM-DD']], key: r => [r.name, r.barangay], extra: {} },
    respondents: { label: 'Census respondents', cols: [['respondent_name', 'name', 't', 'Text'], ['barangay', 'barangay', 'b', 'Official barangay name (62)'], ['animals', 'animals', 'n', 'Whole number'], ['animal_condition', 'condition', E.cd], ['program_interest', 'interest', E.pi], ['source', 'source', CV.SRC], ['census_date', 'date', 'd', 'YYYY-MM-DD']], key: r => [r.name, r.barangay], extra: { registered: false } },
    households: { label: 'Households visited', cols: [['household_head', 'name', 't', 'Text'], ['barangay', 'barangay', 'b', 'Official barangay name (62)'], ['paravet', 'paravet', 't', 'Paravet name'], ['animals_recorded', 'animals', 'n', 'Whole number'], ['source', 'source', ['Paravet census', 'Paravet pre-listing']], ['visit_date', 'date', 'd', 'YYYY-MM-DD']], key: r => [r.name, r.barangay, r.date], extra: {} },
    animals: { label: 'Census animals', cols: [['species', 'species', E.sp], ['sex', 'sex', E.sx], ['animal_condition', 'condition', E.cd], ['owner_name', 'owner', 't', 'Text'], ['barangay', 'barangay', 'b', 'Official barangay name (62)'], ['source', 'source', CV.SRC], ['census_date', 'date', 'd', 'YYYY-MM-DD']], key: r => [r.species, r.sex, r.condition, r.owner, r.barangay, r.date], extra: {} },
    stubs: { label: 'Stubs', cols: [['stub_ref', 'id', 't', 'Unique stub reference'], ['type', 'type', ['Physical · 1 per pet', 'Digital · 1 per owner']], ['owner_name', 'owner', 't', 'Text'], ['pets', 'pets', 't', 'Pet name(s)'], ['barangay', 'barangay', 'b', 'Official barangay name (62)'], ['program', 'program', ['Kapon', 'Anti-rabies', 'Microchip', 'All of the above']], ['source', 'source', CV.SRC], ['status', 'status', ['Issued', 'Registered', 'Attended', 'Completed']], ['date_issued', 'date', 'd', 'YYYY-MM-DD']], key: r => [r.id], extra: {} },
    services: { label: 'Services', cols: [['service_date', 'date', 'd', 'YYYY-MM-DD'], ['barangay', 'barangay', 'b', 'Official barangay name (62)'], ['owner_name', 'owner', 't', 'Text'], ['pet_name', 'pet', 't', 'Text'], ['species', 'species', E.sp], ['service', 'service', ['Kapon', 'Anti-rabies', 'Microchip']], ['outcome', 'outcome', ['Completed', 'Incomplete']]], key: r => [r.date, r.owner, r.pet, r.service], extra: {} },
    programs: { label: 'Programs', cols: [['barangay', 'barangay', 'b', 'Official barangay name (62)'], ['program', 'program', ['Kapon', 'Anti-rabies', 'Microchip', 'All of the above']], ['program_date', 'date', 'd', 'YYYY-MM-DD'], ['slots', 'slots', 'n', 'Whole number'], ['booked', 'booked', 'n', 'Whole number'], ['status', 'status', ['Draft', 'Pending approval', 'Approved', 'Scheduled', 'Active', 'Completed', 'Cancelled']], ['paravet', 'paravet', 't', 'Paravet name']], key: r => [r.barangay, r.date], extra: {} },
    participants: { label: 'Program-day participants', cols: [['owner_name', 'owner', 't', 'Text'], ['mobile', 'mobile', 'm', '09XX-XXX-XXXX'], ['pet_name', 'pet', 't', 'Text'], ['species', 'species', E.sp], ['sex', 'sex', E.sx], ['age_years', 'age', 'a', 'Number 0–30'], ['service', 'service', 't', 'Services'], ['source', 'source', CV.SRC], ['stage', 'stage', ['Not yet arrived', 'Registration', 'Anesthetic', 'Clean up', 'Surgery', 'Recovery', 'Completed', 'Incomplete']], ['program_date', 'date', 'd', 'YYYY-MM-DD']], key: r => [r.owner, r.pet, r.date], extra: {} }
  };
  let ds = 'owners', recs = [], idx = {}, fileName = '';
  const csvQ = v => `"${String(v == null ? '' : v).replace(/"/g, '""')}"`;
  const dl = (n, t) => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['\ufeff' + t], { type: 'text/csv' })); a.download = n; a.click(); URL.revokeObjectURL(a.href); };
  function parse(t) { t = t.replace(/^\ufeff/, ''); const rows = []; let r = [], f = '', q = false; for (let i = 0; i < t.length; i++) { const c = t[i]; if (q) { if (c === '"') { if (t[i + 1] === '"') { f += '"'; i++; } else q = false; } else f += c; } else if (c === '"') q = true; else if (c === ',') { r.push(f); f = ''; } else if (c === '\n' || c === '\r') { if (c === '\r' && t[i + 1] === '\n') i++; r.push(f); rows.push(r); r = []; f = ''; } else f += c; } if (q) return null; if (f !== '' || r.length) { r.push(f); rows.push(r); } return rows.filter(x => x.some(y => y.trim() !== '')); }
  function cell(c, v) {
    v = v.trim(); const t = c[2]; if (!v) return c[4] ? { v: '', empty: 1 } : { e: 'is required' };
    if (Array.isArray(t)) { const m = t.find(x => x.toLowerCase() === v.toLowerCase()); return m ? { v: m } : { e: 'must be one of: ' + t.join(' | ') }; }
    if (t === 'b' || t === 'p') { const m = CV.brFind(v) || (t === 'p' && /^all \(rotating\)$/i.test(v) ? 'All (rotating)' : ''); return m ? { v: m } : { e: 'is not an official barangay name' }; }
    if (t === 'm') { const d = v.replace(/\D/g, ''); return /^09\d{9}$/.test(d) ? { v: `${d.slice(0, 4)}-${d.slice(4, 7)}-${d.slice(7)}` } : { e: 'must be a PH mobile number like 0917-123-4567' }; }
    if (t === 'd') { const dd = new Date(v + 'T00:00:00Z'); return /^\d{4}-\d{2}-\d{2}$/.test(v) && !isNaN(dd) && dd.toISOString().slice(0, 10) === v ? { v } : { e: 'must be a real date written YYYY-MM-DD' }; }
    if (t === 'n') return /^\d+$/.test(v) ? { v: +v } : { e: 'must be a whole number' };
    if (t === 'a') return /^\d+(\.\d+)?$/.test(v) && +v <= 30 ? { v: +v } : { e: 'must be a number from 0 to 30' };
    return { v };
  }
  function analyze(rec, seen) {
    const s = S[ds]; rec.v = Object.assign({}, s.extra); rec.errs = []; rec.anoms = []; rec.empty = 0; rec.match = null; rec.diffs = []; rec.fills = [];
    s.cols.forEach((c, j) => { const x = cell(c, rec.raw[j] || ''); if (x.e) rec.errs.push(`${c[0]}: “${(rec.raw[j] || '').trim()}” ${x.e}`); else { rec.v[c[1]] = x.v; if (x.empty) rec.empty++; } });
    if (rec.errs.length) { rec.status = 'invalid'; return rec; }
    const v = rec.v; if (v.date && v.date > TODAY) rec.anoms.push('Date is in the future'); if (v.date && v.date < '2020-01-01') rec.anoms.push('Date is before 2020'); if (+v.age > 20) rec.anoms.push('Age is above 20 years'); if (ds === 'respondents' && v.animals > 15) rec.anoms.push('More than 15 animals for one respondent');
    if (ds === 'owners' && v.status === 'Registered' && !v.date) rec.anoms.push('Registered without a date');
    const k = s.key(v).join('|').toLowerCase(); if (seen) { if (seen.has(k)) { rec.status = 'infile'; return rec; } seen.add(k); }
    const m = idx[k]; rec.match = m || null;
    if (m) s.cols.forEach(c => { const ex = m[c[1]], im = v[c[1]]; if (im === '' || im == null) return; if (ex === '' || ex == null) rec.fills.push(c[1]); else if (CV.norm(String(ex)) !== CV.norm(String(im))) rec.diffs.push(c[1]); });
    rec.status = !m ? 'new' : rec.diffs.length ? 'conflict' : rec.fills.length ? 'fill' : 'identical'; return rec;
  }
  const LBL = { new: 'New', conflict: 'Conflict', fill: 'Fills empty fields', identical: 'Identical', invalid: 'Invalid', infile: 'Duplicate in file' };
  const flagged = r => r.status === 'invalid' || r.status === 'conflict' || r.status === 'infile' || r.anoms.length;
  function summary() {
    const c = k => recs.filter(r => r.status === k).length, sim = recs.filter(r => r.match).length, an = recs.filter(r => r.anoms.length).length, em = recs.reduce((a, r) => a + r.empty, 0), ok = recs.filter(r => !['invalid', 'infile'].includes(r.status) && !r.skip).length;
    $('imResult').innerHTML = `<div class="card"><h2>Import report · ${esc(fileName)}</h2><p><strong>Your imported data has ${sim.toLocaleString()} similar record${sim === 1 ? '' : 's'} to the current records.</strong> ${c('conflict')} conflict with existing values, ${c('fill')} would fill empty fields, ${c('identical')} are identical.${em ? ` ${em} empty optional field${em > 1 ? 's' : ''} in the file.` : ''}${an ? ` ${an} record${an > 1 ? 's have' : ' has'} unusual values.` : ''}</p><div class="stats cs-tabs">${[[recs.length, 'Rows read'], [c('new'), 'New records'], [sim, 'Similar to current'], [c('conflict'), 'Conflicts'], [c('invalid'), 'Invalid rows'], [an, 'Unusual values']].map(([n, l]) => `<div class="stat"><div class="num">${n}</div><div class="label">${l}</div></div>`).join('')}</div><p class="muted">Nothing has been imported yet. Choose how to apply the ${ok} usable rows:</p><div class="toolbar"><button class="btn" id="imReplace" type="button">Replace</button><button class="btn" id="imMerge" type="button">Merge</button><button class="cv-btn" id="imInspect" type="button">Inspect anomalies</button><button class="cv-btn" id="imCancel" type="button">Cancel</button></div><p class="muted"><strong>Replace:</strong> imported values overwrite matching current records; new rows are added. <strong>Merge:</strong> only empty fields of matching records are filled from the file; new rows are added; existing values are kept.</p></div>`;
    $('imReplace').disabled = $('imMerge').disabled = !ok;
  }
  const snapshot = label => CV.write('cityvet.restorepoint', { t: new Date().toISOString(), label, extra: CVData.ext(), overrides: CVData.ov(), archived: CVData.archAll() });
  async function apply(mode) {
    const use = recs.filter(r => !['invalid', 'infile', 'identical'].includes(r.status) && !r.skip && r.choice !== 'existing'), nw = use.filter(r => r.status === 'new'), mt = use.filter(r => r.match);
    const ok = await CVDialog.confirm(mode === 'replace' ? 'Replace matching records' : 'Merge into current records', `${nw.length} new record${nw.length === 1 ? '' : 's'} will be added and ${mt.length} existing record${mt.length === 1 ? '' : 's'} will be ${mode === 'replace' ? 'overwritten with the imported values' : 'completed (empty fields only)'}. A restore point is saved first so you can undo this.`, { danger: mode === 'replace', okLabel: mode === 'replace' ? 'Replace' : 'Merge' });
    if (!ok) return;
    const label = `${S[ds].label} import · ${fileName}`.slice(0, 160);
    const imported = [];
    nw.forEach(r => imported.push(Object.assign({ id: 'IMP-' + crypto.randomUUID() }, r.v)));
    const batchId = CVApi.live && imported.length ? crypto.randomUUID() : null;
    if (!CVApi.live) snapshot(label);
    else if (batchId) CV.write('cityvet.restorepoint', { t: new Date().toISOString(), label, remote: true, dataset: ds, batchId });
    const ex = CVData.ext(), ov = CVData.ov(); ex[ds] = ex[ds] || []; ov[ds] = ov[ds] || {};
    mt.forEach(r => { const f = {}, all = (mode === 'replace' || r.choice === 'imported'); (all ? S[ds].cols.map(c => c[1]).filter(k => r.v[k] !== '' && r.v[k] != null) : r.fills).forEach(k => { f[k] = r.v[k]; }); if (CVApi.live) imported.push(Object.assign({}, r.match, f)); else { const own = (ex[ds] || []).find(x => x.id === r.match.id); if (own) Object.assign(own, f); else ov[ds][r.match.id] = Object.assign(ov[ds][r.match.id] || {}, f); } });
    if (CVApi.live && batchId) await CVApi.importRecords(ds, batchId, label, imported);
    else CV.write('cityvet.extra', ex), CV.write('cityvet.overrides', ov);
    const h = CV.read('cityvet.imports.history', []); h.unshift({ t: new Date().toISOString().slice(0, 16).replace('T', ' '), ds: S[ds].label, datasetKey: ds, batchId, file: fileName, rows: recs.length, added: nw.length, changed: mt.length, mode, skipped: recs.length - nw.length - mt.length }); CV.write('cityvet.imports.history', h.slice(0, 20));
    CV.log('CSV import ' + mode, `${S[ds].label} · ${fileName} · +${nw.length} / ~${mt.length}`);
    CV.notify({ title: `Import complete: ${S[ds].label}`, body: `${nw.length} added, ${mt.length} ${mode === 'replace' ? 'replaced' : 'merged'}, ${recs.length - nw.length - mt.length} skipped.`, detail: `File ${fileName} was applied using ${mode}. ${nw.length} new records were added and ${mt.length} existing records were updated. A restore point was saved; use “Undo last import” in Data quality if needed.`, link: '#/data-quality', from: 'Import' });
    CVDialog.toast('Import applied. A restore point was saved.', 'success'); $('imResult').innerHTML = `<div class="card"><h2>Import applied</h2><p>${nw.length} added · ${mt.length} ${mode === 'replace' ? 'replaced' : 'merged'} · ${recs.length - nw.length - mt.length} skipped.</p></div>`; recs = []; $('imFile').value = ''; history(); window.dispatchEvent(new Event('cv-data'));
  }
  function inspect() {
    const s = S[ds]; let all = false;
    const rowHtml = r => `<tr data-n="${r.n}" class="${r.skip ? 'skipped' : ''}"><td>${r.n}</td><td data-st><span class="pill ${r.status === 'invalid' || r.status === 'infile' ? 'due' : r.status === 'new' || r.status === 'identical' ? 'ok' : ''}">${LBL[r.status]}</span></td><td data-is class="issues">${[...r.errs, ...r.anoms, ...r.diffs.map(k => `${k} differs from current (“${esc(r.match[k])}”)`), ...r.fills.map(k => `${k} fills a blank in the current record`)].map(esc).join('<br/>') || '—'}</td>${s.cols.map((c, j) => `<td><input data-j="${j}" value="${esc(r.raw[j] || '')}" aria-label="${c[0]}"/></td>`).join('')}<td><label class="nowrap"><input type="checkbox" data-skip${r.skip ? ' checked' : ''}/> Skip</label>${r.match && r.status !== 'identical' ? `<select data-ch aria-label="Decision"><option value="">Use chosen mode</option><option value="existing"${r.choice === 'existing' ? ' selected' : ''}>Keep existing</option><option value="imported"${r.choice === 'imported' ? ' selected' : ''}>Use imported</option></select>` : ''}</td></tr>`;
    const body = () => `<div class="table-wrap"><table class="inspect"><thead><tr><th>Row</th><th>Status</th><th>What to check</th>${s.cols.map(c => `<th>${c[0]}</th>`).join('')}<th>Decision</th></tr></thead><tbody>${recs.filter(r => all || flagged(r)).slice(0, 200).map(rowHtml).join('') || '<tr><td colspan="20" class="muted">Nothing to inspect.</td></tr>'}</tbody></table></div>`;
    CVDialog.open({ title: 'Inspect and correct records', size: 'xl', html: `<p class="muted">Edit any value to fix it, skip rows you don’t want, or decide per conflict. Showing up to 200 rows.</p><label class="nowrap"><input type="checkbox" id="insAll"/> Show every row, not only flagged ones</label><div id="insBody">${body()}</div>`, actions: [{ label: 'Done', primary: true, value: 1 }], onOpen: ov => {
      const seen = () => { const st = new Set(); recs.forEach(r => { if (r.status !== 'invalid') { const k = S[ds].key(r.v).join('|').toLowerCase(); st.add(k); } }); return null; };
      ov.querySelector('#insAll').addEventListener('change', e => { all = e.target.checked; ov.querySelector('#insBody').innerHTML = body(); });
      ov.addEventListener('change', e => { const tr = e.target.closest('tr[data-n]'); if (!tr) return; const r = recs.find(x => x.n === +tr.dataset.n); if (e.target.matches('[data-j]')) { r.raw[+e.target.dataset.j] = e.target.value; analyze(r, null); const t = document.createElement('tbody'); t.innerHTML = rowHtml(r); tr.querySelector('[data-st]').innerHTML = t.querySelector('[data-st]').innerHTML; tr.querySelector('[data-is]').innerHTML = t.querySelector('[data-is]').innerHTML; } else if (e.target.matches('[data-skip]')) { r.skip = e.target.checked; tr.classList.toggle('skipped', r.skip); } else if (e.target.matches('[data-ch]')) r.choice = e.target.value; });
    } }).then(summary);
  }
  function history() { const h = CV.read('cityvet.imports.history', []); $('imHist').innerHTML = h.length ? `<table><thead><tr><th>When</th><th>Dataset</th><th>File</th><th>Mode</th><th>Rows</th><th>Added</th><th>Changed</th><th>Skipped</th></tr></thead><tbody>${h.map(x => `<tr><td>${x.t}</td><td>${esc(x.ds)}</td><td>${esc(x.file)}</td><td>${x.mode}</td><td>${x.rows}</td><td>${x.added}</td><td>${x.changed}</td><td>${x.skipped}</td></tr>`).join('')}</tbody></table>` : '<p class="muted">No imports yet.</p>'; }
  function show() { const s = S[ds]; $('imSet').value = ds; $('imHeaders').innerHTML = `<table><thead><tr><th>#</th><th>Column header (exact)</th><th>Required format</th></tr></thead><tbody>${s.cols.map((c, i) => `<tr><td>${i + 1}</td><td><code>${c[0]}</code></td><td>${Array.isArray(c[2]) ? esc(c[2].join(' | ')) : esc(c[3])}</td></tr>`).join('')}</tbody></table>`; $('imResult').innerHTML = ''; $('imFile').value = ''; recs = []; }
  $('imSet').addEventListener('change', e => { ds = e.target.value; show(); });
  $('imTemplate').addEventListener('click', () => dl(`template-${ds}.csv`, S[ds].cols.map(c => c[0]).join(',') + '\r\n'));
  $('imExport').addEventListener('click', () => { const s = S[ds], rows = D[ds].rows; dl(`export-${ds}.csv`, [s.cols.map(c => c[0]).join(','), ...rows.map(x => s.cols.map(c => csvQ(x[c[1]])).join(','))].join('\r\n')); CV.log('Export CSV', `${rows.length} ${s.label}`); });
  $('imClear').addEventListener('click', async () => { if (!(await CVDialog.confirm('Remove imported rows', `Remove all imported ${S[ds].label} rows and reverse changes made by imports?`, { danger: true, okLabel: 'Remove' }))) return; try { if (CVApi.live) { const h = CV.read('cityvet.imports.history', []), batches = h.filter(x => x.datasetKey === ds && x.batchId).map(x => x.batchId); if (!batches.length) return CVDialog.toast('There are no imports from this browser session to remove.', 'info'); await CVApi.undoImports(ds, batches); CV.write('cityvet.imports.history', h.filter(x => x.datasetKey !== ds)); } else { const ex = CVData.ext(), ov = CVData.ov(); delete ex[ds]; delete ov[ds]; CV.write('cityvet.extra', ex); CV.write('cityvet.overrides', ov); } CV.log('Imports removed', S[ds].label); window.dispatchEvent(new Event('cv-data')); CVDialog.toast('Imported data removed.', 'success'); } catch (e) { CVDialog.toast(e.message, 'error'); } });
  $('imFile').addEventListener('change', async e => {
    const f = e.target.files[0]; if (!f) return; fileName = f.name; const err = (t, m) => CVDialog.alert(t, m, 'error');
    if (!/\.csv$/i.test(f.name)) return err('Only CSV files are accepted', 'In Excel use Save As → CSV UTF-8 (Comma delimited).');
    const rows = parse(await f.text()), s = S[ds];
    if (!rows) return err('Unclosed quotation mark', 'The file has a quotation mark that is never closed. Check the CSV and try again.');
    if (!rows.length) return err('Empty file', 'The file has no rows.');
    if (rows[0].length === 1 && /;|\t/.test(rows[0][0])) return err('Wrong separator', 'The file looks semicolon- or tab-separated. Save it as “CSV UTF-8 (Comma delimited)”.');
    const want = s.cols.map(c => c[0]), got = rows[0].map(h => h.trim().toLowerCase());
    if (want.join() !== got.join()) { const miss = want.filter(h => !got.includes(h)), extra = got.filter(h => !want.includes(h)); return err('Header row does not match', `The header row does not match the ${s.label} template.` + (miss.length ? ` Missing: ${miss.join(', ')}.` : '') + (extra.length ? ` Unexpected: ${extra.join(', ')}.` : '') + (!miss.length && !extra.length ? ' Columns must be in the template order.' : '')); }
    if (rows.length - 1 > 3000) return err('File too large', 'The file has more than 3,000 data rows. Split it into smaller files.');
    idx = {}; D[ds].rows.forEach(x => { idx[s.key(x).join('|').toLowerCase()] = x; });
    const seen = new Set(); recs = rows.slice(1).map((raw, i) => analyze({ n: i + 2, raw: raw.length === want.length ? raw : [...raw, ...Array(Math.max(0, want.length - raw.length)).fill('')].slice(0, want.length), skip: false, choice: '' }, seen));
    rows.slice(1).forEach((raw, i) => { if (raw.length !== want.length) { recs[i].errs.unshift(`expected ${want.length} columns but found ${raw.length}`); recs[i].status = 'invalid'; } });
    CV.log('CSV uploaded (not applied)', `${s.label} · ${f.name} · ${recs.length} rows`); summary();
  });
  $('imResult').addEventListener('click', e => { const b = e.target.closest('button'); if (!b) return; if (b.id === 'imReplace') apply('replace').catch(x => CVDialog.toast(x.message, 'error')); else if (b.id === 'imMerge') apply('merge').catch(x => CVDialog.toast(x.message, 'error')); else if (b.id === 'imInspect') inspect(); else if (b.id === 'imCancel') { recs = []; $('imResult').innerHTML = ''; $('imFile').value = ''; CVDialog.toast('Import cancelled. Nothing was changed.', 'info'); } });
  window.addEventListener('cv-show', () => { let d = null; try { d = sessionStorage.getItem('cityvet.importDs'); sessionStorage.removeItem('cityvet.importDs'); } catch (x) {} if (d && S[d] && $('imSet').offsetParent !== null) { ds = d; show(); } history(); });
  show(); history();
})();
