-- e-Kapon auth/accounts API: fresh-install bootstrap.
-- Run this before db/001_create_api_role.sql. No existing objects or data are
-- dropped. Passwords are stored only as pgcrypto bcrypt hashes.

BEGIN;

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE SCHEMA IF NOT EXISTS ekapon;
REVOKE ALL ON SCHEMA ekapon FROM PUBLIC;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ekapon_admin') THEN
        CREATE ROLE ekapon_admin NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA ekapon, extensions TO ekapon_admin;

CREATE TYPE ekapon.account_type AS ENUM ('Admin', 'Encoder', 'Paravet', 'User');
CREATE TYPE ekapon.account_status AS ENUM (
    'Active',
    'Disabled',
    'Locked',
    'Temporary password pending',
    'Temporary password expired',
    'Password reset required'
);

CREATE TABLE ekapon.barangays (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acronym          text NOT NULL UNIQUE,
    name             text NOT NULL UNIQUE,
    district         smallint NOT NULL CHECK (district IN (1, 2)),
    district_label   text GENERATED ALWAYS AS (
        CASE district WHEN 1 THEN '1st District' ELSE '2nd District' END
    ) STORED,
    zip              text NOT NULL CHECK (zip IN ('3023', '3024')),
    CONSTRAINT barangays_district_zip_check CHECK (
        (district = 1 AND zip = '3023') OR (district = 2 AND zip = '3024')
    )
);

CREATE SEQUENCE ekapon.account_key_seq AS bigint START WITH 1;

CREATE TABLE ekapon.accounts (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_key         text UNIQUE,
    username            text,
    account_type        ekapon.account_type NOT NULL,
    first_name          text NOT NULL CHECK (length(btrim(first_name)) BETWEEN 1 AND 80),
    middle_name         text CHECK (middle_name IS NULL OR length(middle_name) <= 80),
    last_name           text NOT NULL CHECK (length(btrim(last_name)) BETWEEN 1 AND 80),
    suffix              text CHECK (suffix IS NULL OR length(suffix) <= 80),
    full_name           text GENERATED ALWAYS AS (
        btrim(
            btrim(first_name)
            || CASE WHEN NULLIF(btrim(middle_name), '') IS NULL THEN '' ELSE ' ' || btrim(middle_name) END
            || ' ' || btrim(last_name)
            || CASE WHEN NULLIF(btrim(suffix), '') IS NULL THEN '' ELSE ' ' || btrim(suffix) END
        )
    ) STORED,
    mobile              text CHECK (mobile IS NULL OR mobile ~ '^09[0-9]{2}[- ]?[0-9]{3}[- ]?[0-9]{4}$'),
    barangay_id         integer REFERENCES ekapon.barangays(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    paravet_id          bigint,
    owner_id            bigint,
    status              ekapon.account_status NOT NULL DEFAULT 'Active',
    password_hash       text,
    failed_login_count  integer NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
    locked_until        timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    last_login_at       timestamptz,
    archived_at         timestamptz,
    CONSTRAINT accounts_identity_check CHECK (
        (account_type IN ('Admin', 'Encoder') AND username IS NOT NULL AND account_key IS NULL)
        OR
        (account_type IN ('Paravet', 'User') AND username IS NULL AND account_key IS NOT NULL
         AND barangay_id IS NOT NULL)
    ),
    CONSTRAINT accounts_password_hash_check CHECK (
        password_hash IS NULL OR password_hash LIKE '$2%'
    )
);

CREATE UNIQUE INDEX accounts_active_person_uq
    ON ekapon.accounts (
        account_type, barangay_id, lower(btrim(first_name)), lower(btrim(last_name))
    )
    WHERE archived_at IS NULL AND account_type IN ('Paravet', 'User');
CREATE UNIQUE INDEX accounts_username_uq
    ON ekapon.accounts (lower(username)) WHERE username IS NOT NULL;

CREATE TABLE ekapon.temp_credentials (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      bigint NOT NULL REFERENCES ekapon.accounts(id) ON DELETE CASCADE,
    password_hash   text NOT NULL CHECK (password_hash LIKE '$2%'),
    created_at      timestamptz NOT NULL DEFAULT now(),
    expires_at      timestamptz NOT NULL,
    failed_attempts integer NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 3),
    locked_at       timestamptz,
    used_at         timestamptz,
    destroyed_at    timestamptz,
    CONSTRAINT temp_credentials_expiry_check CHECK (expires_at > created_at)
);
CREATE INDEX temp_credentials_live_idx
    ON ekapon.temp_credentials (account_id, expires_at DESC)
    WHERE used_at IS NULL AND destroyed_at IS NULL;

CREATE TABLE ekapon.login_attempts (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_identifier text NOT NULL,
    account_id       bigint REFERENCES ekapon.accounts(id) ON DELETE SET NULL,
    method           text NOT NULL CHECK (method IN ('permanent', 'temporary')),
    success          boolean NOT NULL,
    reason           text,
    ip               inet,
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX login_attempts_ip_time_idx
    ON ekapon.login_attempts (ip, created_at DESC) WHERE success = false;
CREATE INDEX login_attempts_account_time_idx
    ON ekapon.login_attempts (account_id, created_at DESC);

CREATE TABLE ekapon.audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  text NOT NULL,
    record_id   text,
    operation   text NOT NULL,
    account_id  bigint,
    old_data    jsonb,
    new_data    jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_record_time_idx ON ekapon.audit_log (table_name, record_id, created_at DESC);

CREATE TABLE ekapon.settings (
    setting_name  text PRIMARY KEY,
    setting_value text NOT NULL
);
INSERT INTO ekapon.settings (setting_name, setting_value)
VALUES ('max_login_attempts', '5');

CREATE FUNCTION ekapon.setting_int(p_name text)
RETURNS integer
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, ekapon
AS $$
    SELECT COALESCE(
        (SELECT setting_value::integer FROM ekapon.settings WHERE setting_name = p_name),
        CASE p_name WHEN 'max_login_attempts' THEN 5 ELSE 0 END
    )
$$;

CREATE FUNCTION ekapon.find_barangay(p_name text)
RETURNS integer
LANGUAGE sql STABLE
SET search_path = pg_catalog, ekapon
AS $$
    SELECT b.id
      FROM ekapon.barangays AS b
     WHERE regexp_replace(translate(lower(b.name), '–—', '--'), '[[:space:]]+', ' ', 'g')
         = regexp_replace(translate(lower(btrim(p_name)), '–—', '--'), '[[:space:]]+', ' ', 'g')
     LIMIT 1
$$;

CREATE FUNCTION ekapon.audit_row()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, ekapon
AS $$
DECLARE
    v_old jsonb;
    v_new jsonb;
    v_id text;
    v_actor bigint;
BEGIN
    v_actor := NULLIF(current_setting('app.account_id', true), '')::bigint;
    IF TG_OP <> 'INSERT' THEN
        v_old := to_jsonb(OLD) - ARRAY['password_hash'];
        v_id := to_jsonb(OLD)->>'id';
    END IF;
    IF TG_OP <> 'DELETE' THEN
        v_new := to_jsonb(NEW) - ARRAY['password_hash'];
        v_id := to_jsonb(NEW)->>'id';
    END IF;

    INSERT INTO ekapon.audit_log (table_name, record_id, operation, account_id, old_data, new_data)
    VALUES (TG_TABLE_NAME, v_id, TG_OP, v_actor, v_old, v_new);
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END
$$;

CREATE FUNCTION ekapon.set_account_key()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, ekapon
AS $$
DECLARE
    v_zip text;
    v_prefix text;
    v_mobile text;
    v_key_number bigint;
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.account_key IS DISTINCT FROM NEW.account_key THEN
        RAISE EXCEPTION 'Account keys cannot be changed.' USING ERRCODE = '22023';
    END IF;
    IF TG_OP = 'INSERT' AND NEW.account_type IN ('Paravet', 'User') THEN
        IF NEW.barangay_id IS NULL THEN
            RAISE EXCEPTION 'A barangay is required for portal accounts.' USING ERRCODE = '23502';
        END IF;
        SELECT zip INTO STRICT v_zip FROM ekapon.barangays WHERE id = NEW.barangay_id;
        v_prefix := CASE NEW.account_type WHEN 'Paravet' THEN 'PV' ELSE 'US' END;
        v_key_number := nextval('ekapon.account_key_seq');
        NEW.account_key := v_prefix
            || to_char(clock_timestamp() AT TIME ZONE 'Asia/Manila', 'YYYY')
            || '-TMP' || lpad(v_key_number::text, greatest(3, length(v_key_number::text)), '0')
            || '-' || v_zip;
    END IF;
    IF NEW.mobile IS NOT NULL THEN
        v_mobile := regexp_replace(NEW.mobile, '[- ]', '', 'g');
        NEW.mobile := substr(v_mobile, 1, 4) || '-' || substr(v_mobile, 5, 3) || '-' || substr(v_mobile, 8, 4);
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END
$$;

CREATE TRIGGER accounts_set_key
    BEFORE INSERT OR UPDATE ON ekapon.accounts
    FOR EACH ROW EXECUTE FUNCTION ekapon.set_account_key();
CREATE TRIGGER accounts_audit
    AFTER INSERT OR UPDATE OR DELETE ON ekapon.accounts
    FOR EACH ROW EXECUTE FUNCTION ekapon.audit_row();
CREATE TRIGGER temp_credentials_audit
    AFTER INSERT OR UPDATE OR DELETE ON ekapon.temp_credentials
    FOR EACH ROW EXECUTE FUNCTION ekapon.audit_row();

CREATE FUNCTION ekapon.log_activity(p_action text, p_target text)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, ekapon
AS $$
DECLARE
    v_actor bigint;
BEGIN
    v_actor := NULLIF(current_setting('app.account_id', true), '')::bigint;
    INSERT INTO ekapon.audit_log (table_name, record_id, operation, account_id, new_data)
    VALUES ('activity', p_target, 'ACTIVITY', v_actor, jsonb_build_object('action', p_action));
END
$$;

CREATE FUNCTION ekapon.log_login_attempt(
    p_login text, p_account_id bigint, p_method text, p_success boolean, p_reason text, p_ip inet
)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, ekapon
AS $$
BEGIN
    INSERT INTO ekapon.login_attempts (login_identifier, account_id, method, success, reason, ip)
    VALUES (left(COALESCE(p_login, ''), 64), p_account_id, p_method, p_success, p_reason, p_ip);
END
$$;

CREATE FUNCTION ekapon.recent_failed_logins(p_ip inet, p_minutes integer)
RETURNS integer
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, ekapon
AS $$
    SELECT count(*)::integer
      FROM ekapon.login_attempts
     WHERE p_ip IS NOT NULL AND ip = p_ip AND success = false
       AND created_at >= now() - make_interval(mins => greatest(COALESCE(p_minutes, 0), 0))
$$;

CREATE FUNCTION ekapon.issue_temp_password(p_account_id bigint)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, ekapon, extensions
AS $$
DECLARE
    v_account ekapon.accounts%ROWTYPE;
    v_password text := '';
    v_alphabet constant text := 'ABCDEFGHJKLMNPQRTUVWXYabcdefghjkmnpqrtuvwxy346789';
    v_byte integer;
    v_limit integer := (256 / length(v_alphabet)) * length(v_alphabet);
BEGIN
    SELECT * INTO STRICT v_account FROM ekapon.accounts WHERE id = p_account_id FOR UPDATE;
    IF v_account.account_type NOT IN ('Paravet', 'User')
       OR v_account.status = 'Disabled'
       OR v_account.archived_at IS NOT NULL THEN
        RAISE EXCEPTION 'Temporary passwords are only for active portal accounts.' USING ERRCODE = '22023';
    END IF;

    UPDATE ekapon.temp_credentials
       SET destroyed_at = COALESCE(destroyed_at, now())
     WHERE account_id = p_account_id AND used_at IS NULL AND destroyed_at IS NULL;

    WHILE length(v_password) < 8 LOOP
        v_byte := get_byte(extensions.gen_random_bytes(1), 0);
        IF v_byte < v_limit THEN
            v_password := v_password || substr(v_alphabet, (v_byte % length(v_alphabet)) + 1, 1);
        END IF;
    END LOOP;
    v_password := substr(v_password, 1, 4) || '-' || substr(v_password, 5, 4);

    INSERT INTO ekapon.temp_credentials (account_id, password_hash, expires_at)
    VALUES (p_account_id, extensions.crypt(v_password, extensions.gen_salt('bf', 12)), now() + interval '15 minutes');

    UPDATE ekapon.accounts
       SET status = 'Temporary password pending', password_hash = NULL,
           failed_login_count = 0, locked_until = NULL
     WHERE id = p_account_id;
    RETURN v_password;
END
$$;

CREATE FUNCTION ekapon.verify_temp_password(p_account_key text, p_password text, p_ip inet DEFAULT NULL)
RETURNS TABLE (o_ok boolean, o_reason text, o_account_id bigint, o_attempts_left integer)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, ekapon, extensions
AS $$
DECLARE
    v_account ekapon.accounts%ROWTYPE;
    v_credential ekapon.temp_credentials%ROWTYPE;
    v_left integer;
BEGIN
    SELECT * INTO v_account
      FROM ekapon.accounts
     WHERE account_key = upper(btrim(p_account_key)) AND archived_at IS NULL
     FOR UPDATE;
    IF NOT FOUND THEN
        PERFORM ekapon.log_login_attempt(p_account_key, NULL, 'temporary', false, 'unknown account', p_ip);
        RETURN QUERY SELECT false, 'invalid'::text, NULL::bigint, NULL::integer;
        RETURN;
    END IF;
    IF v_account.status = 'Locked' OR v_account.locked_until > now() THEN
        PERFORM ekapon.log_login_attempt(p_account_key, v_account.id, 'temporary', false, 'locked', p_ip);
        RETURN QUERY SELECT false, 'locked'::text, v_account.id, 0;
        RETURN;
    END IF;
    IF v_account.status = 'Temporary password expired' THEN
        PERFORM ekapon.log_login_attempt(p_account_key, v_account.id, 'temporary', false, 'expired', p_ip);
        RETURN QUERY SELECT false, 'expired'::text, v_account.id, NULL::integer;
        RETURN;
    END IF;

    SELECT * INTO v_credential
      FROM ekapon.temp_credentials
     WHERE account_id = v_account.id AND used_at IS NULL AND destroyed_at IS NULL
     ORDER BY created_at DESC, id DESC
     LIMIT 1 FOR UPDATE;
    IF NOT FOUND OR v_account.status NOT IN ('Temporary password pending', 'Temporary password expired') THEN
        PERFORM ekapon.log_login_attempt(p_account_key, v_account.id, 'temporary', false, 'invalid', p_ip);
        RETURN QUERY SELECT false, 'invalid'::text, v_account.id, NULL::integer;
        RETURN;
    END IF;
    IF v_credential.locked_at IS NOT NULL THEN
        PERFORM ekapon.log_login_attempt(p_account_key, v_account.id, 'temporary', false, 'locked', p_ip);
        RETURN QUERY SELECT false, 'locked'::text, v_account.id, 0;
        RETURN;
    END IF;
    IF v_credential.expires_at <= now() THEN
        UPDATE ekapon.temp_credentials SET destroyed_at = now() WHERE id = v_credential.id;
        UPDATE ekapon.accounts SET status = 'Temporary password expired' WHERE id = v_account.id;
        PERFORM ekapon.log_login_attempt(p_account_key, v_account.id, 'temporary', false, 'expired', p_ip);
        RETURN QUERY SELECT false, 'expired'::text, v_account.id, NULL::integer;
        RETURN;
    END IF;

    IF extensions.crypt(COALESCE(p_password, ''), v_credential.password_hash) = v_credential.password_hash THEN
        UPDATE ekapon.temp_credentials SET used_at = now() WHERE id = v_credential.id;
        UPDATE ekapon.accounts SET status = 'Password reset required' WHERE id = v_account.id;
        PERFORM ekapon.log_login_attempt(p_account_key, v_account.id, 'temporary', true, NULL, p_ip);
        RETURN QUERY SELECT true, 'ok'::text, v_account.id, NULL::integer;
        RETURN;
    END IF;

    v_left := greatest(3 - v_credential.failed_attempts - 1, 0);
    UPDATE ekapon.temp_credentials
       SET failed_attempts = failed_attempts + 1,
           locked_at = CASE WHEN failed_attempts + 1 >= 3 THEN now() ELSE locked_at END
     WHERE id = v_credential.id;
    IF v_left = 0 THEN
        UPDATE ekapon.accounts SET status = 'Locked' WHERE id = v_account.id;
    END IF;
    PERFORM ekapon.log_login_attempt(p_account_key, v_account.id, 'temporary', false,
                                     CASE WHEN v_left = 0 THEN 'locked' ELSE 'invalid' END, p_ip);
    RETURN QUERY SELECT false, CASE WHEN v_left = 0 THEN 'locked' ELSE 'invalid' END::text, v_account.id, v_left;
END
$$;

CREATE FUNCTION ekapon.set_permanent_password(p_account_id bigint, p_password text)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, ekapon, extensions
AS $$
DECLARE
    v_status ekapon.account_status;
BEGIN
    IF p_password IS NULL OR length(p_password) < 8 OR length(p_password) > 200
       OR p_password !~ '[A-Za-z]' OR p_password !~ '[0-9]' THEN
        RAISE EXCEPTION 'Password must be at least 8 characters and contain a letter and a number.'
            USING ERRCODE = '22023';
    END IF;
    SELECT status INTO STRICT v_status FROM ekapon.accounts WHERE id = p_account_id FOR UPDATE;
    IF v_status NOT IN ('Active', 'Password reset required') THEN
        RAISE EXCEPTION 'This account cannot set a permanent password in its current state.'
            USING ERRCODE = '22023';
    END IF;
    UPDATE ekapon.accounts
       SET password_hash = extensions.crypt(p_password, extensions.gen_salt('bf', 12)),
           status = 'Active', failed_login_count = 0, locked_until = NULL
     WHERE id = p_account_id;
    UPDATE ekapon.temp_credentials
       SET destroyed_at = COALESCE(destroyed_at, now())
     WHERE account_id = p_account_id AND used_at IS NULL AND destroyed_at IS NULL;
END
$$;

CREATE FUNCTION ekapon.verify_password(p_login text, p_password text, p_ip inet DEFAULT NULL)
RETURNS TABLE (o_ok boolean, o_reason text, o_account_id bigint)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, ekapon, extensions
AS $$
DECLARE
    v_account ekapon.accounts%ROWTYPE;
    v_max_attempts integer := ekapon.setting_int('max_login_attempts');
    v_reason text;
BEGIN
    SELECT * INTO v_account
      FROM ekapon.accounts
     WHERE (lower(username) = lower(p_login) OR account_key = upper(btrim(p_login)))
       AND archived_at IS NULL
     FOR UPDATE;
    IF NOT FOUND THEN
        PERFORM ekapon.log_login_attempt(p_login, NULL, 'permanent', false, 'unknown account', p_ip);
        RETURN QUERY SELECT false, 'invalid'::text, NULL::bigint;
        RETURN;
    END IF;
    v_reason := CASE
        WHEN v_account.status = 'Disabled' THEN 'disabled'
        WHEN v_account.status = 'Locked' OR v_account.locked_until > now() THEN 'locked'
        WHEN v_account.status IN ('Temporary password pending', 'Temporary password expired') THEN 'use_temporary_password'
        WHEN v_account.status = 'Password reset required' THEN 'must_reset'
    END;
    IF v_reason IS NOT NULL THEN
        PERFORM ekapon.log_login_attempt(p_login, v_account.id, 'permanent', false, v_reason, p_ip);
        RETURN QUERY SELECT false, v_reason, v_account.id;
        RETURN;
    END IF;

    IF v_account.password_hash IS NOT NULL
       AND extensions.crypt(COALESCE(p_password, ''), v_account.password_hash) = v_account.password_hash THEN
        UPDATE ekapon.accounts
           SET failed_login_count = 0, locked_until = NULL, last_login_at = now()
         WHERE id = v_account.id;
        PERFORM ekapon.log_login_attempt(p_login, v_account.id, 'permanent', true, NULL, p_ip);
        RETURN QUERY SELECT true, 'ok'::text, v_account.id;
        RETURN;
    END IF;

    UPDATE ekapon.accounts
       SET locked_until = CASE WHEN failed_login_count + 1 >= v_max_attempts
                               THEN now() + interval '15 minutes' ELSE locked_until END,
           failed_login_count = CASE WHEN failed_login_count + 1 >= v_max_attempts
                                     THEN 0 ELSE failed_login_count + 1 END
     WHERE id = v_account.id;
    PERFORM ekapon.log_login_attempt(p_login, v_account.id, 'permanent', false, 'invalid', p_ip);
    RETURN QUERY SELECT false, 'invalid'::text, v_account.id;
END
$$;

CREATE FUNCTION ekapon.archive_records(p_table text, p_ids bigint[], p_restore boolean DEFAULT false)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, ekapon
AS $$
DECLARE
    v_count integer;
BEGIN
    IF p_table <> 'accounts' THEN
        RAISE EXCEPTION 'Unsupported archive target.' USING ERRCODE = '22023';
    END IF;
    UPDATE ekapon.accounts
       SET archived_at = CASE WHEN p_restore THEN NULL ELSE now() END
     WHERE id = ANY(COALESCE(p_ids, ARRAY[]::bigint[]))
       AND archived_at IS DISTINCT FROM CASE WHEN p_restore THEN NULL ELSE now() END;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN v_count;
END
$$;

-- Official 62-barangay reference list used by the API.
INSERT INTO ekapon.barangays (name, acronym, district, zip) VALUES
    ('Assumption', 'AS', 2, '3024'),
    ('Bagong Buhay I', 'B1', 2, '3024'),
    ('Bagong Buhay II', 'B2', 2, '3024'),
    ('Bagong Buhay III', 'B3', 2, '3024'),
    ('Citrus', 'CT', 2, '3024'),
    ('Ciudad Real', 'CR', 1, '3023'),
    ('Dulong Bayan', 'DB', 1, '3023'),
    ('Fatima I', 'F1', 2, '3024'),
    ('Fatima II', 'F2', 2, '3024'),
    ('Fatima III', 'F3', 2, '3024'),
    ('Fatima IV', 'F4', 2, '3024'),
    ('Fatima V', 'F5', 2, '3024'),
    ('Francisco Homes–Guijo', 'FG', 1, '3023'),
    ('Francisco Homes–Mulawin', 'FM', 1, '3023'),
    ('Francisco Homes–Narra', 'FN', 1, '3023'),
    ('Francisco Homes–Yakal', 'FY', 1, '3023'),
    ('Gaya-Gaya', 'GG', 1, '3023'),
    ('Graceville', 'GV', 1, '3023'),
    ('Gumaoc Central', 'GC', 1, '3023'),
    ('Gumaoc East', 'GE', 1, '3023'),
    ('Gumaoc West', 'GW', 1, '3023'),
    ('Kaybanban', 'KB', 1, '3023'),
    ('Kaypian', 'KP', 1, '3023'),
    ('Lawang Pari', 'LP', 2, '3024'),
    ('Maharlika', 'MH', 1, '3023'),
    ('Minuyan I', 'M1', 2, '3024'),
    ('Minuyan II', 'M2', 2, '3024'),
    ('Minuyan III', 'M3', 2, '3024'),
    ('Minuyan IV', 'M4', 2, '3024'),
    ('Minuyan Proper', 'MP', 2, '3024'),
    ('Minuyan V', 'M5', 2, '3024'),
    ('Muzon East', 'ME', 1, '3023'),
    ('Muzon Proper', 'MZ', 1, '3023'),
    ('Muzon South', 'MS', 1, '3023'),
    ('Muzon West', 'MW', 1, '3023'),
    ('Paradise III', 'PI', 1, '3023'),
    ('Poblacion', 'PB', 1, '3023'),
    ('Poblacion I', 'P1', 1, '3023'),
    ('San Isidro', 'SI', 1, '3023'),
    ('San Manuel', 'SM', 1, '3023'),
    ('San Martin I', 'S1', 2, '3024'),
    ('San Martin II', 'S2', 2, '3024'),
    ('San Martin III', 'S3', 2, '3024'),
    ('San Martin IV', 'S4', 2, '3024'),
    ('San Martin de Porres', 'SP', 2, '3024'),
    ('San Pedro', 'SD', 2, '3024'),
    ('San Rafael I', 'R1', 2, '3024'),
    ('San Rafael II', 'R2', 2, '3024'),
    ('San Rafael III', 'R3', 2, '3024'),
    ('San Rafael IV', 'R4', 2, '3024'),
    ('San Rafael V', 'R5', 2, '3024'),
    ('San Roque', 'SR', 1, '3023'),
    ('Santa Cruz I', 'C1', 2, '3024'),
    ('Santa Cruz II', 'C2', 2, '3024'),
    ('Santa Cruz III', 'C3', 2, '3024'),
    ('Santa Cruz IV', 'C4', 2, '3024'),
    ('Santa Cruz V', 'C5', 2, '3024'),
    ('Santo Cristo', 'SC', 1, '3023'),
    ('Santo Niño I', 'N1', 2, '3024'),
    ('Santo Niño II', 'N2', 2, '3024'),
    ('Sapang Palay Proper', 'SPP', 2, '3024'),
    ('Tungkong Mangga', 'TM', 1, '3023');

-- Sample staff accounts support the checked-in integration tests. These
-- independent bcrypt hashes correspond to the documented initial password;
-- replace both passwords before the installation is used publicly.
INSERT INTO ekapon.accounts
    (username, account_type, first_name, last_name, password_hash, status)
VALUES
    ('admin', 'Admin', 'City Vet', 'Administrator',
     '$2a$12$HEx1HfiiFCbZZGPZ1XCBXu320YwMFk8aBSqfLDxempCVk8XejJG5W', 'Active'),
    ('encoder', 'Encoder', 'City Vet', 'Encoder',
     '$2a$12$CZ2MGQZK9Gr7yk1myzCnOOnU3F23enFFwQTxg2oyaLIZQ5irI/PVy', 'Active');

-- The current dashboard has several evolving CSV-backed operational modules.
-- Keep their UI-shaped records in a constrained dataset store until each
-- workflow has an independently finalized relational contract.
CREATE TABLE ekapon.dashboard_records (
    id           bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    dataset      text NOT NULL CHECK (dataset IN (
        'owners', 'pets', 'paravets', 'respondents', 'households',
        'animals', 'stubs', 'services', 'programs', 'participants'
    )),
    record_id    text NOT NULL CHECK (length(record_id) BETWEEN 1 AND 100),
    record_data  jsonb NOT NULL CHECK (
        jsonb_typeof(record_data) = 'object'
        AND record_data ? 'id'
        AND record_data->>'id' = record_id
    ),
    archived     boolean NOT NULL DEFAULT false,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (dataset, record_id)
);
CREATE INDEX dashboard_records_listing_idx
    ON ekapon.dashboard_records (dataset, archived, updated_at DESC);
CREATE UNIQUE INDEX dashboard_program_date_unique
    ON ekapon.dashboard_records (lower(record_data->>'barangay'), record_data->>'date')
    WHERE dataset = 'programs' AND NOT archived
      AND COALESCE(record_data->>'status', '') <> 'Cancelled';
CREATE TRIGGER dashboard_records_audit
    AFTER INSERT OR UPDATE OR DELETE ON ekapon.dashboard_records
    FOR EACH ROW EXECUTE FUNCTION ekapon.audit_row();

CREATE TABLE ekapon.dashboard_import_batches (
    batch_id      uuid PRIMARY KEY,
    dataset       text NOT NULL CHECK (dataset IN (
        'owners', 'pets', 'paravets', 'respondents', 'households',
        'animals', 'stubs', 'services', 'programs', 'participants'
    )),
    actor_id      bigint NOT NULL REFERENCES ekapon.accounts(id) ON DELETE RESTRICT,
    label         text NOT NULL CHECK (length(label) BETWEEN 1 AND 160),
    created_at    timestamptz NOT NULL DEFAULT now(),
    undone_at     timestamptz
);
CREATE TABLE ekapon.dashboard_import_items (
    batch_id       uuid NOT NULL REFERENCES ekapon.dashboard_import_batches(batch_id) ON DELETE CASCADE,
    record_id      text NOT NULL,
    existed_before boolean NOT NULL,
    before_data    jsonb,
    before_archived boolean,
    after_data     jsonb NOT NULL,
    PRIMARY KEY (batch_id, record_id),
    CHECK ((existed_before AND before_data IS NOT NULL AND before_archived IS NOT NULL)
           OR (NOT existed_before AND before_data IS NULL AND before_archived IS NULL))
);

CREATE TABLE ekapon.prelistings (
    id             bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    reference      text PRIMARY KEY,
    owner_name     text NOT NULL CHECK (length(btrim(owner_name)) BETWEEN 1 AND 120),
    mobile         text NOT NULL CHECK (mobile ~ '^09[0-9]{2}[- ]?[0-9]{3}[- ]?[0-9]{4}$'),
    barangay_id    integer NOT NULL REFERENCES ekapon.barangays(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    program        text NOT NULL CHECK (program IN ('Kapon (spay / neuter)', 'Anti-rabies', 'Microchip', 'Lahat / All three')),
    pets           jsonb NOT NULL CHECK (jsonb_typeof(pets) = 'array' AND jsonb_array_length(pets) BETWEEN 1 AND 10),
    submitted_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX prelistings_submitted_idx ON ekapon.prelistings (submitted_at DESC);
CREATE TRIGGER prelistings_audit
    AFTER INSERT OR UPDATE OR DELETE ON ekapon.prelistings
    FOR EACH ROW EXECUTE FUNCTION ekapon.audit_row();

-- Expose only the API contract. In particular, password hashes and the
-- temporary-credential table are not readable by the API login role.
GRANT USAGE ON SCHEMA ekapon TO ekapon_admin;
GRANT USAGE ON TYPE ekapon.account_type, ekapon.account_status TO ekapon_admin;
GRANT SELECT ON ekapon.barangays TO ekapon_admin;
GRANT SELECT (
    id, account_key, username, account_type, first_name, middle_name, last_name, suffix,
    full_name, mobile, barangay_id, paravet_id, owner_id, status, created_at,
    last_login_at, archived_at
) ON ekapon.accounts TO ekapon_admin;
GRANT INSERT (username, account_type, first_name, middle_name, last_name, suffix,
              mobile, barangay_id, paravet_id, owner_id)
    ON ekapon.accounts TO ekapon_admin;
GRANT UPDATE (first_name, middle_name, last_name, suffix, mobile, barangay_id,
              failed_login_count, locked_until)
    ON ekapon.accounts TO ekapon_admin;
GRANT DELETE ON ekapon.accounts TO ekapon_admin;
GRANT USAGE, SELECT ON SEQUENCE ekapon.accounts_id_seq, ekapon.account_key_seq,
    ekapon.barangays_id_seq, ekapon.login_attempts_id_seq TO ekapon_admin;
GRANT SELECT (account_id, used_at, destroyed_at, locked_at, expires_at)
    ON ekapon.temp_credentials TO ekapon_admin;
GRANT SELECT (ip) ON ekapon.login_attempts TO ekapon_admin;
GRANT INSERT (login_identifier, method, success, reason, ip)
    ON ekapon.login_attempts TO ekapon_admin;
GRANT DELETE ON ekapon.login_attempts TO ekapon_admin;
GRANT SELECT ON ekapon.audit_log TO ekapon_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ekapon.dashboard_records TO ekapon_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ekapon.dashboard_import_batches,
    ekapon.dashboard_import_items TO ekapon_admin;
GRANT SELECT, INSERT ON ekapon.prelistings TO ekapon_admin;
GRANT USAGE, SELECT ON SEQUENCE ekapon.dashboard_records_id_seq, ekapon.prelistings_id_seq TO ekapon_admin;
GRANT EXECUTE ON FUNCTION ekapon.find_barangay(text),
    ekapon.setting_int(text),
    ekapon.log_activity(text, text),
    ekapon.log_login_attempt(text, bigint, text, boolean, text, inet),
    ekapon.recent_failed_logins(inet, integer),
    ekapon.issue_temp_password(bigint),
    ekapon.verify_temp_password(text, text, inet),
    ekapon.set_permanent_password(bigint, text),
    ekapon.verify_password(text, text, inet),
    ekapon.archive_records(text, bigint[], boolean)
TO ekapon_admin;

REVOKE ALL ON ALL TABLES IN SCHEMA ekapon FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA ekapon FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA ekapon FROM PUBLIC;

COMMIT;
