-- Dashboard data APIs for installations that already have the e-Kapon
-- accounts schema. Fresh installations get these objects from 000_ekapon_schema.sql.
BEGIN;

CREATE TABLE IF NOT EXISTS ekapon.dashboard_records (
    id           bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    dataset      text NOT NULL CHECK (dataset IN (
        'owners', 'pets', 'paravets', 'respondents', 'households',
        'animals', 'stubs', 'services', 'programs', 'participants'
    )),
    record_id    text NOT NULL CHECK (length(record_id) BETWEEN 1 AND 100),
    record_data  jsonb NOT NULL CHECK (
        jsonb_typeof(record_data) = 'object'
        AND record_data ? 'id'
        AND record_data->>'id' = record_id
    ),
    archived     boolean NOT NULL DEFAULT false,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (dataset, record_id)
);
CREATE INDEX IF NOT EXISTS dashboard_records_listing_idx
    ON ekapon.dashboard_records (dataset, archived, updated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS dashboard_program_date_unique
    ON ekapon.dashboard_records (lower(record_data->>'barangay'), record_data->>'date')
    WHERE dataset = 'programs' AND NOT archived
      AND COALESCE(record_data->>'status', '') <> 'Cancelled';

CREATE TABLE IF NOT EXISTS ekapon.dashboard_import_batches (
    batch_id       uuid PRIMARY KEY,
    dataset        text NOT NULL CHECK (dataset IN (
        'owners', 'pets', 'paravets', 'respondents', 'households',
        'animals', 'stubs', 'services', 'programs', 'participants'
    )),
    actor_id       bigint NOT NULL REFERENCES ekapon.accounts(id) ON DELETE RESTRICT,
    label          text NOT NULL CHECK (length(label) BETWEEN 1 AND 160),
    created_at     timestamptz NOT NULL DEFAULT now(),
    undone_at      timestamptz
);
CREATE TABLE IF NOT EXISTS ekapon.dashboard_import_items (
    batch_id        uuid NOT NULL REFERENCES ekapon.dashboard_import_batches(batch_id) ON DELETE CASCADE,
    record_id       text NOT NULL,
    existed_before  boolean NOT NULL,
    before_data     jsonb,
    before_archived boolean,
    after_data      jsonb NOT NULL,
    PRIMARY KEY (batch_id, record_id),
    CHECK ((existed_before AND before_data IS NOT NULL AND before_archived IS NOT NULL)
           OR (NOT existed_before AND before_data IS NULL AND before_archived IS NULL))
);

CREATE TABLE IF NOT EXISTS ekapon.prelistings (
    id            bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    reference     text PRIMARY KEY,
    owner_name    text NOT NULL CHECK (length(btrim(owner_name)) BETWEEN 1 AND 120),
    mobile        text NOT NULL CHECK (mobile ~ '^09[0-9]{2}[- ]?[0-9]{3}[- ]?[0-9]{4}$'),
    barangay_id   integer NOT NULL REFERENCES ekapon.barangays(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    program       text NOT NULL CHECK (program IN ('Kapon (spay / neuter)', 'Anti-rabies', 'Microchip', 'Lahat / All three')),
    pets          jsonb NOT NULL CHECK (jsonb_typeof(pets) = 'array' AND jsonb_array_length(pets) BETWEEN 1 AND 10),
    submitted_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS prelistings_submitted_idx ON ekapon.prelistings (submitted_at DESC);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'dashboard_records_audit' AND tgrelid = 'ekapon.dashboard_records'::regclass) THEN
        CREATE TRIGGER dashboard_records_audit
            AFTER INSERT OR UPDATE OR DELETE ON ekapon.dashboard_records
            FOR EACH ROW EXECUTE FUNCTION ekapon.audit_row();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'prelistings_audit' AND tgrelid = 'ekapon.prelistings'::regclass) THEN
        CREATE TRIGGER prelistings_audit
            AFTER INSERT OR UPDATE OR DELETE ON ekapon.prelistings
            FOR EACH ROW EXECUTE FUNCTION ekapon.audit_row();
    END IF;
END
$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON ekapon.dashboard_records TO ekapon_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ekapon.dashboard_import_batches,
    ekapon.dashboard_import_items TO ekapon_admin;
GRANT SELECT, INSERT ON ekapon.prelistings TO ekapon_admin;
GRANT USAGE, SELECT ON SEQUENCE ekapon.dashboard_records_id_seq,
    ekapon.prelistings_id_seq TO ekapon_admin;

COMMIT;
